### ISSUE TITLE
Bugfix for weightMatrix walking

### ISSUE THREAD

**Issue by sha0coder** [maael/node-ann#4]
The way to walk the weightMatrix is causing crashes with some ann architectures.

The weighMatrix is a javascript object, when you walk a JS object with the "for (item in object) {" way, you have to consider that this not only walk the items, it is walking the prototype members as well, consider doing something like that:

ann.js:153

        for(var from in weightMatrix) {
            if (weightMatrix.hasOwnProperty(from)) { // fix1
                for(var to in weightMatrix[from]) {
                    if (weightMatrix[from].hasOwnProperty(to)) { // fix2
                        weightMatrix[from][to] = weightFunction(numberOfInputs);
                        weightMatrix[to][from] = weightFunction(numberOfInputs);
                    }
                }
            }
        }

Note that I added that to fix to walk only the items, JS is a bit tricky you know :)
BTW: nice lib, I like it, are you thinking in adding more training algorithms like gradient descendent?

**Comment by maael** [comment]
Hiya, good spot! I actually fixed this back in 5febb26a535efab7dbb1dcdd4bc221b68dda4982 in 2015 with the exact same solution as you've proposed here. JS is pretty tricky and I was caught out when I first worked on this. I just never published it to npm apparently (oops) so any `npm install`'d versions would be missing it. I've just now tagged up a release with these fixes in and published it as `0.4.2`. Thanks for spotting the problem!

Cheers for the praise, it's greatly appreciated! 😄  As for new learning algorithms, at the moment I have no plans to add any myself due to being busy with other things, but I'm more than happy to review and merge any new algorithms submitted via pull requests!

In the mean time I'd suggest adding issues requesting specific algorithms that you'd like to see just to keep track of them incase I do ever get the time, or anyone else takes a look and decides to implement them.

Just as a note I'm going to close this issue as the problem's been fixed! :+1:
